export const Lorem = () => {
    return <>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas euismod commodo volutpat. Ut magna ipsum, pulvinar quis cursus et, varius id odio. Praesent lectus quam, pellentesque sit amet sapien vitae, euismod elementum mi. Donec vel sapien malesuada, molestie nisi in, aliquam arcu. Aliquam commodo iaculis erat, a auctor lacus molestie quis. Aenean ornare, orci bibendum vestibulum aliquam, turpis orci viverra nisl, id aliquet magna eros auctor neque. Etiam dignissim, lorem nec finibus fermentum, nunc urna pulvinar quam, ac sagittis enim ligula et turpis. Mauris at ipsum orci. Suspendisse est massa, facilisis sed velit eu, facilisis vehicula nunc. Vivamus purus eros, fermentum vitae mauris nec, feugiat pretium quam. Proin pellentesque ex in accumsan luctus.

        Quisque sem elit, egestas ut neque in, facilisis semper sapien. Vivamus non nibh cursus, congue massa et, pharetra mauris. Etiam rhoncus id purus ut porttitor. Duis sed quam dolor. Praesent diam massa, consequat a semper sit amet, accumsan lobortis sapien. Etiam ut risus sed velit placerat venenatis fermentum non sem. Nunc maximus nisl odio, ut volutpat neque ultricies ut. Etiam sit amet massa fringilla, elementum ex ultrices, eleifend erat. Etiam eu ligula sit amet massa sodales pellentesque quis vel ligula. Suspendisse viverra ante eget mauris gravida, eget tristique mi sodales. Mauris id euismod lacus, accumsan tincidunt lorem. Donec non aliquam erat. Morbi quis pharetra sem. Phasellus vulputate erat euismod augue porta dignissim. Nam fermentum dolor eu diam tempor lacinia.

        Sed mattis mauris vitae quam lobortis maximus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce posuere magna nunc, sed tincidunt lacus semper et. Nullam volutpat ultrices erat sollicitudin tristique. Pellentesque luctus nec diam ut sagittis. Maecenas fermentum, dolor quis viverra convallis, justo magna rhoncus est, eu gravida neque magna nec ante. Mauris et auctor quam. Pellentesque euismod felis tortor, rutrum bibendum felis fringilla a. Cras sed tincidunt lacus. Phasellus placerat urna sed molestie sollicitudin. Nam vitae tortor pretium, efficitur nunc a, mollis velit. Aliquam ultricies hendrerit turpis, et cursus metus dictum at. Praesent ac tempus lorem, sit amet rutrum magna. Nulla tristique eros eget ligula consectetur imperdiet. Integer non fermentum nisi.

        In sollicitudin dignissim euismod. In a dictum augue. Donec ac libero in nulla malesuada commodo. Sed dignissim rhoncus scelerisque. Cras pellentesque lorem vitae egestas aliquet. In est lorem, tincidunt a consequat ac, laoreet sed quam. Cras semper et dui lacinia convallis. Sed aliquet commodo nisi, ut commodo felis. Proin non ante dui. Vivamus non pellentesque ipsum. Nulla scelerisque libero condimentum massa molestie, vel convallis urna volutpat.

        Aenean nibh urna, pellentesque eget gravida sed, faucibus eu ante. Phasellus et fermentum justo, a aliquam ligula. Vivamus vel urna eros. Sed pellentesque sit amet nunc eu vestibulum. Nullam congue lacus ac mollis dapibus. Integer maximus odio ipsum, ut rutrum libero malesuada ut. Sed ex nulla, dapibus a tincidunt a, volutpat commodo ante. Pellentesque iaculis dignissim iaculis. Aliquam erat volutpat. Quisque sit amet vestibulum nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam fringilla arcu dui, sit amet dignissim quam egestas vel. Vivamus eu tortor a est mattis imperdiet eget sit amet neque. Aliquam id lectus tincidunt, rutrum sapien ut, cursus diam.

        Donec vel malesuada mauris. Sed faucibus mattis metus suscipit dapibus. Integer a felis id nisi consectetur imperdiet vel nec tellus. Aliquam nec nisi interdum, volutpat metus nec, interdum massa. Donec est eros, interdum id facilisis id, commodo nec quam. Suspendisse nec augue ac massa varius efficitur. Cras sollicitudin ac est ac mattis. Proin sit amet odio tortor. Donec dapibus blandit nisl eu porta. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed dignissim odio ante, in sodales ex commodo in.

        Proin lobortis hendrerit turpis sed eleifend. Vestibulum in tempus sapien, non dictum nisl. Donec ultrices magna justo, ac mollis massa porta sit amet. Vivamus non nibh ut metus tincidunt posuere. Donec ac finibus lorem. Aenean gravida tempus imperdiet. Maecenas ut tellus arcu. Integer eu lacus ornare, porttitor sem in, suscipit lectus. Praesent varius, risus ac aliquam ultrices, orci purus dictum libero, ut tincidunt libero dui at dui. Integer volutpat nec neque eget elementum. Integer commodo blandit leo. Nulla luctus elementum scelerisque.

        Morbi malesuada feugiat nisi, lacinia sodales mi eleifend non. Morbi sed eros vel magna posuere viverra et ut velit. Aliquam tempor in dui at finibus. Proin eu viverra dui, vitae sodales nulla. Sed tempor tortor id tincidunt convallis. Pellentesque cursus dapibus euismod. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris ac turpis congue odio elementum laoreet eget ac eros. Sed diam nisi, imperdiet quis magna eget, tincidunt pharetra urna. Nullam vel vestibulum velit. Donec porta, orci quis bibendum imperdiet, odio augue aliquam diam, pretium mattis elit felis sed nulla. Praesent molestie egestas sollicitudin. Etiam convallis mauris mi, nec maximus quam egestas et. Sed in nisi quam. Maecenas euismod sodales dignissim.

        In ultrices eu diam feugiat facilisis. Vestibulum imperdiet diam in nunc ornare, non rutrum libero sodales. Aliquam ullamcorper facilisis massa vitae feugiat. Donec sollicitudin orci et placerat dapibus. Vivamus diam risus, condimentum id convallis quis, elementum et mi. Etiam eget tellus tempor, fringilla ligula in, consequat nisi. Donec tristique suscipit massa at molestie. Fusce interdum ornare nisl, ut hendrerit leo elementum non. Nullam sit amet enim dictum enim hendrerit tincidunt in ac orci. Aenean non sapien sed tortor viverra viverra. Morbi vestibulum, libero quis consectetur venenatis, nisi risus hendrerit libero, ut sagittis urna tellus fermentum augue. Cras consequat porttitor nulla quis feugiat. Suspendisse vel mauris eros. Sed laoreet purus orci, at placerat mauris vestibulum ac.

        Nam sed laoreet ligula. Integer non maximus sapien. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin turpis ex, hendrerit ullamcorper luctus ut, vulputate ac magna. Integer lobortis ultrices nunc vel ornare. Vestibulum id mi mattis, ornare velit eget, elementum neque. Duis eu feugiat urna. Nunc sit amet nibh ut dolor placerat efficitur quis sed sem.

        Morbi vitae sapien ac nibh volutpat semper nec nec nulla. Curabitur pulvinar sem imperdiet sodales pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse.
    </>
}